#!/bin/bash

# Custom Rofi Script

#BORDER="#728cbb"
#SEPARATOR="#141414"
#FOREGROUND="#888888"
#BACKGROUND="#141414"
#BACKGROUND_ALT="#1f1f1f"
#HIGHLIGHT_BACKGROUND="#282828"
#HIGHLIGHT_FOREGROUND="#1e88e5"

#BLACK="#000000"
#WHITE="#ffffff"
#RED="#e53935"
#GREEN="#43a047"
#YELLOW="#fdd835"
#BLUE="#1e88e5"
#MAGENTA="#00897b"
#CYAN="#00acc1"
#PINK="#d81b60"
#PURPLE="#8e24aa"
#INDIGO="#3949ab"
#TEAL="#00897b"
#LIME="#c0ca33"
#AMBER="#ffb300"
#ORANGE="#fb8c00"
#BROWN="#6d4c41"
#GREY="#757575"
#BLUE_GREY="#546e7a"
#DEEP_PURPLE="#5e35b1"
#DEEP_ORANGE="#f4511e"
#LIGHT_BLUE="#039be5"
#LIGHT_GREEN="#7cb342"

# Launch Rofi
#rofi -no-lazy-grab -show drun \
#-display-drun "Applications :" -drun-display-format "{name}" \
#-hide-scrollbar true \
#-bw 0 \
#-lines 10 \
#-line-padding 15 \
#-padding 60 \
#-width 30 \
#-xoffset 10 -yoffset 40 \
#-location 1 \
#-fullscreen \
#-columns 4 \
#-show-icons -icon-theme "Papirus" \
#-font "Noto Sans 9" \
#-color-enabled true \
#-color-window "$BACKGROUND,$BORDER,$SEPARATOR" \
#-color-normal "$BACKGROUND_ALT,$FOREGROUND,$BACKGROUND_ALT,$HIGHLIGHT_BACKGROUND,$HIGHLIGHT_FOREGROUND" \
#-color-active "$BACKGROUND,$MAGENTA,$BACKGROUND_ALT,$HIGHLIGHT_BACKGROUND,$HIGHLIGHT_FOREGROUND" \
#-color-urgent "$BACKGROUND,$YELLOW,$BACKGROUND_ALT,$HIGHLIGHT_BACKGROUND,$HIGHLIGHT_FOREGROUND"

# More Options
# -fullscreen \

# Theming help
# color window = background, border, separator
# color normal = background, foreground, background-alt, highlight-background, highlight-foreground
# color active = background, foreground, background-alt, highlight-background, highlight-foreground
# color urgent = background, foreground, background-alt, highlight-background, highlight-foreground









#!/bin/bash

# Custom Rofi Script
#BORDER="#1F1F1F"
#SEPARATOR="#1F1F1F"
#FOREGROUND="#A9ABB0"
#BACKGROUND="#1F1F1F"
#BACKGROUND_ALT="#252525"
#HIGHLIGHT_BACKGROUND="#FF6F00"
#HIGHLIGHT_FOREGROUND="#FFFFFF"


BORDER="#60ffffff"
SEPARATOR="#60ffffff"
FOREGROUND="#012c40"
BACKGROUND="#60ffffff"
BACKGROUND_ALT="#60ffffff"
HIGHLIGHT_BACKGROUND="#007bff"
HIGHLIGHT_FOREGROUND="#FFFFFF"


BLACK="#000000"
WHITE="#ffffff"
RED="#e53935"
GREEN="#43a047"
YELLOW="#fdd835"
BLUE="#1e88e5"
MAGENTA="#00897b"
CYAN="#00acc1"
PINK="#d81b60"
PURPLE="#8e24aa"
INDIGO="#3949ab"
TEAL="#00897b"
LIME="#c0ca33"
AMBER="#ffb300"
ORANGE="#fb8c00"
BROWN="#6d4c41"
GREY="#757575"
BLUE_GREY="#546e7a"
DEEP_PURPLE="#5e35b1"
DEEP_ORANGE="#f4511e"
LIGHT_BLUE="#039be5"
LIGHT_GREEN="#7cb342"

# Launch Rofi
rofi -no-lazy-grab -show drun \
-display-drun "Applications :" -drun-display-format "{name}" \
-hide-scrollbar true \
-bw 0 \
-lines 10 \
-line-padding 10 \
-padding 20 \
-width 39 \
-xoffset 9 -yoffset 44 \
-location 1 \
-columns 2 \
-show-icons -icon-theme "Papirus" \
-font "SFProDisplay-Black 17" \
-color-enabled true \
-color-window "$BACKGROUND,$BORDER,$SEPARATOR" \
-color-normal "$BACKGROUND_ALT,$FOREGROUND,$BACKGROUND_ALT,$HIGHLIGHT_BACKGROUND,$HIGHLIGHT_FOREGROUND" \
#-color-active "$BACKGROUND,$MAGENTA,$BACKGROUND_ALT,$HIGHLIGHT_BACKGROUND,$HIGHLIGHT_FOREGROUND" \
#-color-urgent "$BACKGROUND,$YELLOW,$BACKGROUND_ALT,$HIGHLIGHT_BACKGROUND,$HIGHLIGHT_FOREGROUND"

# More Options
# -fullscreen \

# Theming help
# color window = background, border, separator
# color normal = background, foreground, background-alt, highlight-background, highlight-foreground
# color active = background, foreground, background-alt, highlight-background, highlight-foreground
# color urgent = background, foreground, background-alt, highlight-background, highlight-foreground
